extends:
  - standard
  - standard-react
  - eslint:recommended
plugins:
  - standard
rules:
  jsx-quotes:
    - "error"
    - "prefer-double"
  object-curly-spacing:
    - "warn"
    - "always"
globals:
  chrome: true
  jest: true
  beforeEach: true
  describe: true
  test: true
  expect: true
  it: true
